import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "high", "Undivided; no markings"),
    2: (3, "low", "One or two motorcycles moving in the distance in frame 3"),
    3: (3, "low", "A few cycle rickshaws in motion; count approximate"),
    4: (4, "medium", "Groups of 2-5 people walking across the open carriageway in frames 1-4"),
    5: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    6: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    7: (4, "high", "Banks and offices"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: ("", "low", "No median or centre line visible; island belongs to the roundabout"),
    11: (1, "high", ""),
    12: (16, "medium", "Low kerbed island with painted wall"),
    13: (13, "low", "Buildings and colonnade along the far edge"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (2, "medium", "Kerbed roundabout-like island with heron sculpture"),
    18: (1, "low", ""),
    19: (2, "low", "No markings on the approach; mixed traffic"),
    20: (1, "high", ""),
    21: (2, "low", "No lane markings; estimated"),
    22: (2, "medium", "Road bends around the island"),
    23: (1, "low", "Smooth surface through the bend"),
    24: (1, "high", ""),
    25: (1, "medium", "Smooth asphalt with manhole covers; no visible defects"),
    26: (2, "high", "No lane or edge markings"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (1, "medium", ""),
    32: (1, "high", ""),
    33: (2, "medium", "Cars and vans parked on the right in frames 3-5"),
    34: (4, "medium", "Kerbed paved footpath at the road edge in frame 5"),
    35: (5, "low", ""),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("387810560_9907465534_b2", "387810560_9907465534", "Dilkusha Road", b)
