from vqa_helper import append_batch

b4 = {
    1: (3, "Undivided road", "high", ""),
    2: (2, "1 motorcycle", "medium", "Moving motorcycle (blue Honda Hornet) with rider"),
    3: (2, "1 bicycle", "low", "Decorative cycle rickshaws moving; strict bicycle count uncertain"),
    4: (4, "4 to 5 pedestrians", "medium", ""),
    5: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    6: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    7: (4, "Commercial", "high", "Bank branch and shopfronts visible"),
    8: (4, "Commercial", "high", ""),
    9: (2, "Urban", "high", ""),
    10: ('', 'UNCLASSIFIABLE', "low", "No median or centreline visible; none of the 15 options fit"),
    11: (1, "Not present", "high", ""),
    12: (11, "Tree >=10cm", "medium", "Trees/poles near road edge"),
    13: (13, "Rigid structure or building", "medium", "Bank building with planters close to edge"),
    14: (1, "Not present", "high", ""),
    15: (4, "_None_", "medium", ""),
    16: (4, "_None_", "medium", "Marked zone is a parking lane, not a through-traffic shoulder"),
    17: (12, "_None_", "medium", "No intersection visible in this batch"),
    18: (1, "Not present", "medium", ""),
    19: (3, "Not applicable", "medium", ""),
    20: (1, "Commercial access >=1", "high", ""),
    21: (2, "Two", "low", "No lane markings for travel lanes; estimated"),
    22: (1, "Straight or gently curving", "medium", "Segment near flyover looks straighter than earlier batches"),
    23: (3, "Not applicable", "medium", "Road is straight"),
    24: (1, "0% to <7.5%", "high", ""),
    25: (2, "Medium", "medium", "Patch repairs visible but no large standing-water potholes in this batch"),
    26: (1, "Adequate", "medium", "Consistent white parking-boundary line visible along this segment"),
    27: (1, "Not present", "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "No facility", "high", ""),
    29: (3, "Not applicable", "high", ""),
    30: (7, "No facility", "medium", "No intersection visible"),
    31: (1, "Not present", "high", ""),
    32: (1, "Not present", "high", ""),
    33: (3, "Two side", "high", "Marked parking zone (signed) on one side, motorcycles/cars on the other"),
    34: (6, "Informal path >=1m", "medium", ""),
    35: (6, "Informal path >=1m", "low", "Curb with planters visible but no continuous paved sidewalk"),
    36: (1, "Not present", "high", ""),
    37: (6, "_None_", "high", ""),
    38: (4, "_None_", "high", ""),
    39: (1, "No road works", "high", ""),
    40: (4, "Not applicable (no school at the location)", "high", ""),
    41: (3, "Not applicable (no school at the location)", "high", ""),
}
append_batch("387806314_4894998179_b4", "387806314_4894998179", "Dilkusha Road", b4)
print("appended b4")
