import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "high", "Narrow undivided street; white edge line on one side only"),
    2: (1, "medium", "Motorcycles seen are parked; none moving"),
    3: (1, "low", "Cycle rickshaw/cart parked at the kerb; none clearly moving"),
    4: (2, "low", "One person crossing in frame 1"),
    5: (4, "low", "Group of about 5-7 people walking along the street in frames 7-8; side ambiguous"),
    6: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    7: (4, "high", "Restaurants, shops and offices"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: ("", "low", "No median or centre line; none of the options fit"),
    11: (1, "high", ""),
    12: (13, "low", "Building frontage close to the edge"),
    13: (13, "low", "Shopfronts close to the edge"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (12, "medium", "No intersection visible"),
    18: (1, "medium", ""),
    19: (3, "medium", ""),
    20: (1, "high", "Restaurants and shops open directly onto the street"),
    21: (2, "low", "No lane markings; usable width about two lanes between parking bays and the edge line"),
    22: (1, "high", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (2, "medium", "Rectangular patch scars, worn surface, tyre marks and manholes; no potholes"),
    26: (1, "medium", "White edge line visible on one side, worn in frame 8"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (1, "medium", ""),
    32: (1, "high", ""),
    33: (3, "high", "Cars and motorcycles parked on both sides, with marked bays on the left"),
    34: (5, "low", "Vehicles parked on the verge; no clear footpath"),
    35: (5, "low", "Shopfronts at the edge; no clear footpath"),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("387806314_387813687_b1", "387806314_387813687", "unnamed road", b)
