import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "high", "Undivided; no markings"),
    2: (3, "medium", "Several motorcycles moving in frames 4, 5, 8"),
    3: (5, "medium", "Many cycle rickshaws and rickshaw vans in motion in frames 5-9"),
    4: (4, "medium", "Groups walking across the carriageway in frames 1-2 and 10"),
    5: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    6: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    7: (4, "high", "Offices, banks, airline office"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: ("", "low", "No median or centre line visible; none of the options fit"),
    11: (1, "high", ""),
    12: (13, "medium", "Building frontage close to the edge"),
    13: (13, "medium", "Building frontage close to the edge"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (2, "low", "Small roundabout island with sculpture at the far end of the street"),
    18: (1, "low", ""),
    19: (2, "low", "No markings on the approach; buses parked at the entry"),
    20: (1, "high", ""),
    21: (2, "low", "No lane markings; estimated"),
    22: (1, "high", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (1, "medium", "Smooth asphalt, no visible defects"),
    26: (2, "high", "No lane or edge markings"),
    27: (2, "medium", "Street lamp posts visible in frames 6 and 9"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (1, "medium", ""),
    32: (1, "high", ""),
    33: (3, "high", "Buses, vans and trucks parked on both sides"),
    34: (4, "low", "Footpath at the road edge on the right"),
    35: (5, "low", ""),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("387810560_9907465534_b1", "387810560_9907465534", "Dilkusha Road", b)
