from vqa_helper import append_batch

b = {
    1: (3, "Undivided road", "high", ""),
    2: (1, "_None_", "medium", "No motorcycles observed moving through traffic in this batch"),
    3: (1, "_None_", "medium", "Large bicycle parking rack visible but no bicycles observed moving"),
    4: (4, "4 to 5 pedestrians", "medium", ""),
    5: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    6: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    7: (4, "Commercial", "high", ""),
    8: (4, "Commercial", "high", ""),
    9: (2, "Urban", "high", ""),
    10: ('', 'UNCLASSIFIABLE', "low", "No median or centreline visible; none of the 15 options fit"),
    11: (1, "Not present", "high", ""),
    12: (13, "Rigid structure or building", "medium", "Shopfronts and bicycle-rack stand close to edge"),
    13: (13, "Rigid structure or building", "medium", "Parked cars and buildings close to edge"),
    14: (1, "Not present", "high", ""),
    15: (4, "_None_", "medium", ""),
    16: (4, "_None_", "medium", ""),
    17: (12, "_None_", "medium", "No intersection visible in this batch"),
    18: (1, "Not present", "medium", ""),
    19: (3, "Not applicable", "medium", ""),
    20: (1, "Commercial access >=1", "high", ""),
    21: (2, "Two", "low", "No lane markings for travel lanes; estimated"),
    22: (1, "Straight or gently curving", "high", ""),
    23: (3, "Not applicable", "high", "Road is straight"),
    24: (1, "0% to <7.5%", "high", ""),
    25: (3, "Poor", "high", "Extensive surface wear/ravelling with exposed aggregate and staining across most frames"),
    26: (1, "Adequate", "medium", "Consistent white parking-boundary line visible along this segment"),
    27: (1, "Not present", "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "No facility", "high", ""),
    29: (3, "Not applicable", "high", ""),
    30: (7, "No facility", "medium", "No intersection visible"),
    31: (1, "Not present", "high", ""),
    32: (1, "Not present", "high", ""),
    33: (3, "Two side", "high", ""),
    34: (6, "Informal path >=1m", "medium", ""),
    35: (6, "Informal path >=1m", "medium", ""),
    36: (1, "Not present", "high", ""),
    37: (6, "_None_", "high", ""),
    38: (4, "_None_", "medium", "Bicycle parking rack present but not a dedicated lane/path facility"),
    39: (1, "No road works", "high", ""),
    40: (4, "Not applicable (no school at the location)", "high", ""),
    41: (3, "Not applicable (no school at the location)", "high", ""),
}
append_batch("387813463_387813687_b1", "387813463_387813687", "unnamed road", b)
print("appended road2 b1")
