import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "low", "Wide open plaza/roundabout area, no markings"),
    2: (3, "low", "Two motorcycles moving in the distance in frame 1"),
    3: (3, "medium", "One or two moving cycle rickshaws per frame, more parked"),
    4: (5, "medium", "Group of about 5-6 people crossing the open carriageway in frame 1"),
    5: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    6: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    7: (4, "high", "Banks, offices and food stalls"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: ("", "low", "No median or centre line; central island belongs to the roundabout"),
    11: (1, "high", ""),
    12: (16, "low", "Kerbed island with railing on the left in frame 1"),
    13: (17, "low", "Open edge with parked rickshaws"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (2, "medium", "Central island with railing and posters: roundabout-like junction"),
    18: (1, "low", ""),
    19: (2, "low", "No markings or delineation; chaotic mixed traffic"),
    20: (1, "high", ""),
    21: (4, "low", "Very wide open pavement area with no lane markings; estimated"),
    22: (2, "medium", "Road wraps around the central island"),
    23: (1, "low", "Smooth surface through the bend"),
    24: (1, "high", ""),
    25: (1, "medium", "Smooth worn asphalt, no visible defects"),
    26: (2, "medium", "No lane or edge markings; only a faint edge line near the parking area in frame 2"),
    27: (2, "low", "Street light pole visible on the far side in frame 1"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (2, "low", "Railing on the island in frame 1"),
    32: (1, "high", ""),
    33: (2, "low", "Rickshaws and cars parked on one side"),
    34: (5, "low", ""),
    35: (5, "low", ""),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("4894998175_4894998179_b1", "4894998175_4894998179", "unnamed road", b)
