import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "low", "Wide open road; planter kerb on one side in frames 1-3 but no clear median"),
    2: (4, "medium", "Several motorcycles moving in frames 8-10, many more parked"),
    3: (4, "low", "Several cycle rickshaws in motion or waiting in frames 4-9; count approximate"),
    4: (4, "medium", "Groups of 2-5 people standing or walking across the open carriageway in frames 8-10"),
    5: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    6: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    7: (4, "high", "Banks and offices"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: ("", "low", "No median or centre line clearly visible; none of the options fit"),
    11: (1, "high", ""),
    12: (16, "low", "Low kerbed planter with shrubs in frames 1-3"),
    13: (13, "low", "Building frontage behind the parked vehicles"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (10, "low", "Traffic signals visible ahead in frames 4-5; open junction in frames 8-9"),
    18: (1, "low", ""),
    19: (2, "medium", "No markings at the junction; cracked patch and drain in frame 10"),
    20: (1, "high", "Bank frontage"),
    21: (3, "low", "Wide carriageway with no lane markings; estimated"),
    22: (1, "high", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (2, "medium", "Stained exposed-aggregate surface; cracked patch, puddle and drain grate in frame 10"),
    26: (2, "medium", "Only a white edge line near the kerb; no centre or lane lines"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "medium", "No crossing marking visible although many people cross"),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (1, "medium", ""),
    32: (1, "high", ""),
    33: (3, "low", "Cars parked on the left and an SUV parked on the right in frame 10"),
    34: (5, "low", ""),
    35: (4, "medium", "Paved footpath directly at the road edge in frame 10"),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("387813463_6139734197_b1", "387813463_6139734197", "Dilkusha Road", b)
