from vqa_helper import append_batch

b3 = {
    1: (3, "Undivided road", "high", ""),
    2: (1, "_None_", "medium", "No motorcycles seen moving through traffic in this batch (only parked)"),
    3: (2, "1 bicycle", "low", "Cycle rickshaws pulled/ridden; strict bicycle count uncertain"),
    4: (4, "4 to 5 pedestrians", "medium", ""),
    5: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    6: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    7: (4, "Commercial", "high", ""),
    8: (4, "Commercial", "high", ""),
    9: (2, "Urban", "high", ""),
    10: ('', 'UNCLASSIFIABLE', "low", "No median or centreline visible; none of the 15 options fit"),
    11: (1, "Not present", "high", ""),
    12: (11, "Tree >=10cm", "medium", "Trees near road edge"),
    13: (13, "Rigid structure or building", "medium", "Curb/buildings and dense motorcycle parking close to edge"),
    14: (1, "Not present", "high", ""),
    15: (4, "_None_", "medium", ""),
    16: (3, "Narrow 0m to <1m", "low", "One frame shows a curbed sidewalk edge with drain grate - possible narrow paved shoulder/curb strip"),
    17: (12, "_None_", "medium", "No intersection visible in this batch"),
    18: (1, "Not present", "medium", ""),
    19: (3, "Not applicable", "medium", ""),
    20: (1, "Commercial access >=1", "high", ""),
    21: (2, "Two", "low", "No lane markings; estimated"),
    22: (2, "Moderate", "medium", "Visible curve/bend in road in several frames"),
    23: (2, "Poor", "medium", "Curve area surface rough/patched"),
    24: (1, "0% to <7.5%", "high", ""),
    25: (3, "Poor", "high", "Multiple standing-water potholes and patch repairs visible"),
    26: (2, "Poor", "medium", "No consistent lane/edge markings"),
    27: (1, "Not present", "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "No facility", "high", ""),
    29: (3, "Not applicable", "high", ""),
    30: (7, "No facility", "medium", "No intersection visible"),
    31: (1, "Not present", "high", ""),
    32: (1, "Not present", "high", ""),
    33: (3, "Two side", "high", "Cars on one side, dense motorcycle parking on the other"),
    34: (6, "Informal path >=1m", "medium", ""),
    35: (4, "Sidewalk 0m to <1m from road", "low", "One frame shows a curbed sidewalk with drain grate on this side"),
    36: (1, "Not present", "high", ""),
    37: (6, "_None_", "high", "Dense motorcycle parking but no dedicated lane/path"),
    38: (4, "_None_", "high", ""),
    39: (1, "No road works", "high", "Patches are past repairs, no active work/workers visible"),
    40: (4, "Not applicable (no school at the location)", "high", ""),
    41: (3, "Not applicable (no school at the location)", "high", ""),
}
append_batch("387806314_4894998179_b3", "387806314_4894998179", "Dilkusha Road", b3)
print("appended b3")
