import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (1, "low", "Divided road with planter median; carriageway A/B cannot be told apart"),
    2: (3, "medium", "One rider moving in each of frames 7 and 9, more parked"),
    3: (1, "medium", ""),
    4: (3, "medium", "One person crossing in frame 7 plus two walking at the right edge"),
    5: (2, "low", "Median side; pedestrian-captured, side ambiguous"),
    6: (2, "low", "Footpath side; a few people standing or walking"),
    7: (4, "high", "Bank Asia and offices"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: (6, "medium", "Raised planter with shrubs, trees and low railing, roughly 1-3 m wide"),
    11: (1, "high", ""),
    12: (11, "medium", "Trees planted in the median"),
    13: (16, "low", "Kerb with concrete slabs at the footpath edge"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (12, "medium", "No intersection visible"),
    18: (1, "medium", ""),
    19: (3, "medium", ""),
    20: (1, "high", "Bank and shop frontage"),
    21: (2, "medium", "Wide carriageway with edge line; truck parked at the kerb"),
    22: (1, "high", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (1, "medium", "Smooth asphalt"),
    26: (1, "medium", "White edge line along the kerb"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (2, "low", "Low railing on the median planter"),
    32: (1, "high", ""),
    33: (2, "medium", "Delivery truck and motorcycles parked at the kerb"),
    34: (5, "low", "Median kerb only"),
    35: (4, "low", "Footpath directly beside the road behind kerb blocks"),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("9907465534_9907465538_b1", "9907465534_9907465538", "Dilkusha Road", b)
