import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (1, "low", "Divided road with raised planter median; carriageway A/B cannot be told apart"),
    2: (2, "low", "One rider on a motorcycle in frame 2, others parked"),
    3: (1, "medium", ""),
    4: (2, "low", "One person about to cross in frame 2"),
    5: (1, "medium", ""),
    6: (1, "low", ""),
    7: (4, "high", "Banks and shops"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: (6, "medium", "Raised planter/concrete kerb median with trees, roughly 1-3 m wide"),
    11: (1, "high", ""),
    12: (11, "medium", "Trees planted in the median"),
    13: (13, "low", "Buildings along the far edge"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (12, "medium", "No intersection visible"),
    18: (1, "medium", ""),
    19: (3, "medium", ""),
    20: (1, "medium", "Bank and shop access"),
    21: (2, "medium", "Wide carriageway with edge line; truck parked on the median side"),
    22: (1, "high", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (1, "medium", "Smooth asphalt"),
    26: (1, "medium", "White edge line along the median kerb"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (2, "low", "Low railing on the median planter in frame 1"),
    32: (1, "high", ""),
    33: (2, "medium", "Delivery truck parked on the median side"),
    34: (5, "low", "Median kerb only"),
    35: (5, "low", "Not visible"),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("264891930_9907465538_b1", "264891930_9907465538", "Dilkusha Road", b)
