import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "medium", "Undivided; no markings"),
    2: (1, "low", "No moving motorcycle visible"),
    3: (4, "low", "Several cycle rickshaws and cycles moving or parked; count approximate"),
    4: (4, "medium", "Several people crossing the open carriageway"),
    5: (2, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    6: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    7: (4, "medium", "Commercial frontage and stalls"),
    8: (4, "medium", ""),
    9: (2, "high", ""),
    10: ("", "low", "No median or centre line visible; none of the options fit"),
    11: (1, "high", ""),
    12: (16, "low", "Raised kerbed island on the left in frame 1"),
    13: (17, "low", "Parked bus and rickshaws along the edge"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (2, "low", "Kerbed island of the roundabout-like plaza in frame 1"),
    18: (1, "low", ""),
    19: (2, "low", "Potholes and no markings on the approach"),
    20: (1, "low", ""),
    21: (2, "low", "No lane markings; estimated"),
    22: (2, "low", "Road bends around the island"),
    23: (2, "low", "Bend has potholes and standing water"),
    24: (1, "high", ""),
    25: (3, "high", "Potholes with standing water and worn patched surface"),
    26: (2, "high", "No lane or edge markings"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (1, "medium", ""),
    32: (1, "high", ""),
    33: (2, "medium", "Bus and rickshaws parked on one side"),
    34: (5, "low", ""),
    35: (5, "low", ""),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("264891930_4894998175_b3", "264891930_4894998175", "unnamed road", b)
