from vqa_helper import append_batch

b2 = {
    1: (3, "Undivided road", "high", ""),
    2: (2, "1 motorcycle", "medium", "One motorcycle (red Honda Hornet) actively ridden through frame"),
    3: (2, "1 bicycle", "low", "Cycle rickshaws in motion; strict bicycle count uncertain"),
    4: (5, "6 to 7 pedestrians", "medium", "Group near vendor stall plus others walking"),
    5: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    6: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    7: (4, "Commercial", "high", ""),
    8: (4, "Commercial", "high", ""),
    9: (2, "Urban", "high", ""),
    10: ('', 'UNCLASSIFIABLE', "low", "No median or centreline visible; none of the 15 options fit"),
    11: (1, "Not present", "high", ""),
    12: (11, "Tree >=10cm", "medium", "Mature trees near road edge"),
    13: (13, "Rigid structure or building", "medium", "Shopfronts/buildings close to road edge"),
    14: (1, "Not present", "high", ""),
    15: (4, "_None_", "medium", ""),
    16: (4, "_None_", "medium", ""),
    17: (12, "_None_", "medium", "No intersection visible in this batch"),
    18: (1, "Not present", "medium", ""),
    19: (3, "Not applicable", "medium", ""),
    20: (1, "Commercial access >=1", "high", ""),
    21: (2, "Two", "low", "No lane markings; estimated"),
    22: (2, "Moderate", "medium", "Visible bend in road ahead in some frames"),
    23: (2, "Poor", "medium", "Curve area has rough patched/gravel surface"),
    24: (1, "0% to <7.5%", "high", ""),
    25: (3, "Poor", "high", "Standing-water potholes and rough patched/gravel repair strips visible"),
    26: (2, "Poor", "medium", "No consistent lane/edge markings"),
    27: (1, "Not present", "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "No facility", "high", ""),
    29: (3, "Not applicable", "high", ""),
    30: (7, "No facility", "medium", "No intersection visible"),
    31: (1, "Not present", "high", ""),
    32: (1, "Not present", "high", ""),
    33: (3, "Two side", "high", ""),
    34: (6, "Informal path >=1m", "medium", ""),
    35: (6, "Informal path >=1m", "medium", ""),
    36: (1, "Not present", "high", ""),
    37: (6, "_None_", "high", ""),
    38: (4, "_None_", "high", ""),
    39: (1, "No road works", "high", "Patches are past repairs, no active work/workers visible"),
    40: (4, "Not applicable (no school at the location)", "high", ""),
    41: (3, "Not applicable (no school at the location)", "high", ""),
}
append_batch("387806314_4894998179_b2", "387806314_4894998179", "Dilkusha Road", b2)
print("appended b2")
