import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "medium", "Undivided; dashed centre line, yellow railing on a raised edge platform"),
    2: (3, "medium", "Motorcycles moving in frames 2 and 8, many more parked"),
    3: (4, "medium", "Several cycle rickshaws, rickshaw vans and a loaded bicycle in motion"),
    4: (5, "medium", "Groups of 2-3 people walking across the carriageway in frames 2, 3, 7, 8"),
    5: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    6: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    7: (4, "high", "Banks and shops"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: (11, "medium", "Dashed white centre line visible in frames 8-10"),
    11: (1, "high", ""),
    12: (13, "low", "Bank and shop frontage behind the parked vehicles"),
    13: (16, "medium", "Concrete kerb blocks and yellow metal railing on the left"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (12, "medium", "No intersection visible"),
    18: (1, "medium", ""),
    19: (3, "medium", ""),
    20: (1, "high", ""),
    21: (2, "medium", "Two lanes about the dashed centre line"),
    22: (1, "high", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (1, "medium", "Mostly smooth asphalt; damp patch and small patch near the kerb in frames 1, 4, 6"),
    26: (1, "medium", "Dashed centre line present; worn in places"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersecting-road crossing facility visible"),
    31: (2, "high", "Yellow railing along the left edge"),
    32: (1, "high", ""),
    33: (2, "high", "Cars and motorcycles parked on one side"),
    34: (4, "low", "Paved footpath at the edge behind parked vehicles"),
    35: (1, "medium", "Raised platform behind yellow railing on the left"),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("264891930_387813463_b1", "264891930_387813463", "Dilkusha Road", b)
