from vqa_helper import append_batch

b5 = {
    1: (3, "Undivided road", "high", ""),
    2: (1, "_None_", "medium", "Motorcycles present are parked; none observed moving in this batch"),
    3: (1, "_None_", "medium", "No clear bicycle/rickshaw in motion; only a hand-pulled cart seen"),
    4: (4, "4 to 5 pedestrians", "medium", ""),
    5: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    6: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    7: (4, "Commercial", "high", "Bank/office area"),
    8: (4, "Commercial", "high", ""),
    9: (2, "Urban", "high", ""),
    10: ('', 'UNCLASSIFIABLE', "low", "No median or centreline visible; none of the 15 options fit"),
    11: (1, "Not present", "high", ""),
    12: (13, "Rigid structure or building", "medium", "Office/bank buildings close to edge, fewer trees in this batch"),
    13: (13, "Rigid structure or building", "medium", "Concrete planter box and buildings close to edge"),
    14: (1, "Not present", "high", ""),
    15: (4, "_None_", "medium", ""),
    16: (4, "_None_", "medium", ""),
    17: (12, "_None_", "medium", "No intersection visible in this batch"),
    18: (1, "Not present", "medium", ""),
    19: (3, "Not applicable", "medium", ""),
    20: (1, "Commercial access >=1", "high", ""),
    21: (2, "Two", "low", "No lane markings for travel lanes; estimated"),
    22: (2, "Moderate", "medium", "Slight bend visible near the planter/curb section"),
    23: (2, "Poor", "medium", "Patch/pothole near curb at the curve"),
    24: (1, "0% to <7.5%", "high", ""),
    25: (2, "Medium", "medium", "Patch repairs and a small pothole near a drain, but smoother overall than earlier batches"),
    26: (1, "Adequate", "medium", "Consistent white line visible along this segment"),
    27: (1, "Not present", "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "No facility", "high", ""),
    29: (3, "Not applicable", "high", ""),
    30: (7, "No facility", "medium", "No intersection visible"),
    31: (1, "Not present", "high", ""),
    32: (1, "Not present", "high", ""),
    33: (3, "Two side", "high", ""),
    34: (6, "Informal path >=1m", "medium", ""),
    35: (6, "Informal path >=1m", "low", "Concrete planter/curb present but no continuous paved sidewalk"),
    36: (1, "Not present", "high", ""),
    37: (6, "_None_", "high", ""),
    38: (4, "_None_", "high", ""),
    39: (1, "No road works", "high", ""),
    40: (4, "Not applicable (no school at the location)", "high", ""),
    41: (3, "Not applicable (no school at the location)", "high", ""),
}
append_batch("387806314_4894998179_b5", "387806314_4894998179", "Dilkusha Road", b5)
print("appended b5 - Dilkusha Road (387806314_4894998179) complete: 5/5 batches")
