import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "high", "Undivided road with dashed centre line"),
    2: (2, "low", "One scooter visible in frame 9"),
    3: (3, "low", "Several cycle rickshaws in motion; strict bicycle count uncertain"),
    4: (4, "medium", "Several people walking across and along the carriageway in frames 6-10"),
    5: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    6: (4, "low", "Bazaar frontage on the railing side"),
    7: (4, "high", "Banks, shops and bazaar"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: (11, "high", "Dashed white centre line"),
    11: (1, "high", ""),
    12: (13, "medium", "Building frontage behind the parked cars"),
    13: (16, "low", "Yellow metal railing on a low kerb"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (12, "medium", "No junction clearly visible"),
    18: (1, "medium", ""),
    19: (3, "medium", ""),
    20: (1, "high", "Banks and shopfronts"),
    21: (2, "medium", "Two lanes about the dashed centre line"),
    22: (1, "high", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (1, "medium", "Mostly smooth asphalt; small patch around a manhole in frames 1-2"),
    26: (1, "medium", "Centre line and left edge line visible, worn in places"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersection visible"),
    31: (2, "high", "Yellow railing along the kerb"),
    32: (1, "high", ""),
    33: (2, "high", "Parked cars on one side only"),
    34: (5, "low", "Building side hidden by parked cars"),
    35: (1, "medium", "Raised footpath behind railing on the left"),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("264891930_4894998175_b1", "264891930_4894998175", "unnamed road", b)
