import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (1, "low", "Divided road (raised planter median on far side); carriageway A/B cannot be told apart"),
    2: (2, "medium", "One motorcycle ridden past in frame 1"),
    3: (2, "low", "Cycle-rickshaw van in frame 1, rickshaw/bicycle behind median; strict count uncertain"),
    4: (3, "medium", "Man crossing the carriageway in frame 3 plus the photographer's group"),
    5: (1, "low", "Median side; pedestrian-captured, side ambiguous"),
    6: (2, "low", "Kerb side; one pedestrian on far side in frame 1"),
    7: (4, "high", "Shops/offices beyond median"),
    8: (4, "medium", ""),
    9: (2, "high", ""),
    10: (6, "medium", "Raised planter with shrubs and railing, roughly 1-3 m wide"),
    11: (1, "high", ""),
    12: (11, "medium", "Trees planted in the median"),
    13: (17, "low", "Kerb side mostly hidden by parked vehicles"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", "Parked vehicles occupy the edge"),
    17: (12, "medium", "No intersection visible"),
    18: (1, "medium", ""),
    19: (3, "medium", ""),
    20: (1, "low", "Shopfronts across the median; access on this side not visible"),
    21: (2, "medium", "Wide one-way carriageway with cars in two positions"),
    22: (1, "high", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (2, "low", "Aged asphalt with exposed aggregate, no potholes visible"),
    26: (1, "low", "Faint white edge line next to the median kerb in frame 3"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", "No intersection visible"),
    31: (2, "medium", "Iron railing on the median"),
    32: (1, "high", ""),
    33: (2, "medium", "Cars parked along the kerb side"),
    34: (5, "medium", "Median kerb only"),
    35: (5, "low", "Kerb side not visible"),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("387813463_387813687_b4", "387813463_387813687", "unnamed road", b)
