import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vqa_helper import append_batch

b = {
    1: (3, "medium", "Undivided; no median or centre line"),
    2: (1, "medium", "Motorcycles seen are parked; none clearly moving"),
    3: (4, "low", "Many cycle rickshaws and a few bicycles in motion; count approximate"),
    4: (5, "medium", "Many people crossing the carriageway in frames 3, 8, 9, 10"),
    5: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    6: (3, "low", "Driver/passenger side ambiguous for pedestrian-captured images"),
    7: (4, "high", "Shops, banks, bazaar"),
    8: (4, "high", ""),
    9: (2, "high", ""),
    10: ("", "low", "No median or centre line visible; none of the options fit"),
    11: (1, "high", ""),
    12: (13, "low", "Buildings and parked vehicles along the edge"),
    13: (16, "low", "Kerb and low railing in early frames"),
    14: (1, "high", ""),
    15: (4, "medium", ""),
    16: (4, "medium", ""),
    17: (2, "low", "Approach to a roundabout-like plaza with a central island in frame 9"),
    18: (1, "low", ""),
    19: (2, "low", "No markings or delineation on the approach; chaotic mixed traffic"),
    20: (1, "high", ""),
    21: (2, "low", "No lane markings; estimated"),
    22: (1, "medium", ""),
    23: (3, "high", "Road is straight"),
    24: (1, "high", ""),
    25: (2, "medium", "Oil stains, patched asphalt and a manhole patch; no large potholes"),
    26: (2, "medium", "No centre line; only a faint edge line in early frames"),
    27: (1, "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "high", ""),
    29: (3, "high", ""),
    30: (7, "medium", ""),
    31: (2, "low", "Railing along the kerb in early frames"),
    32: (1, "high", ""),
    33: (2, "medium", "Cars and motorcycles parked mainly on one side"),
    34: (4, "medium", "Raised footpath directly at the road edge"),
    35: (1, "low", "Kerb with railing on the left in early frames"),
    36: (1, "high", ""),
    37: (6, "high", ""),
    38: (4, "high", ""),
    39: (1, "high", ""),
    40: (4, "high", ""),
    41: (3, "high", ""),
}
append_batch("264891930_4894998175_b2", "264891930_4894998175", "unnamed road", b)
