from vqa_helper import append_batch

b = {
    1: (3, "Undivided road", "high", ""),
    2: (2, "1 motorcycle", "medium", "One motorcycle with two riders observed moving through the frame"),
    3: (1, "_None_", "medium", "Only hand-pulled carts observed; no bicycle in motion"),
    4: (4, "4 to 5 pedestrians", "medium", ""),
    5: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    6: (3, "2 to 3 pedestrians", "low", "driver/passenger-side ambiguous for pedestrian-captured images"),
    7: (4, "Commercial", "high", ""),
    8: (4, "Commercial", "high", ""),
    9: (2, "Urban", "high", ""),
    10: ('', 'UNCLASSIFIABLE', "low", "No median or centreline visible; none of the 15 options fit"),
    11: (1, "Not present", "high", ""),
    12: (13, "Rigid structure or building", "medium", "Raised curb and shopfronts close to edge"),
    13: (13, "Rigid structure or building", "medium", "Parked motorcycles and buildings close to edge"),
    14: (1, "Not present", "high", ""),
    15: (4, "_None_", "medium", ""),
    16: (4, "_None_", "medium", ""),
    17: (12, "_None_", "medium", "No intersection visible in this batch"),
    18: (1, "Not present", "medium", ""),
    19: (3, "Not applicable", "medium", ""),
    20: (1, "Commercial access >=1", "high", ""),
    21: (2, "Two", "low", "No lane markings for travel lanes; estimated"),
    22: (1, "Straight or gently curving", "high", ""),
    23: (3, "Not applicable", "high", "Road is straight"),
    24: (1, "0% to <7.5%", "high", ""),
    25: (3, "Poor", "high", "Extensive surface wear, staining and patching across most frames"),
    26: (1, "Adequate", "medium", "Consistent white line visible along this segment"),
    27: (1, "Not present", "low", "No lighting fixtures identifiable; daytime images"),
    28: (7, "No facility", "high", ""),
    29: (3, "Not applicable", "high", ""),
    30: (7, "No facility", "medium", "No intersection visible"),
    31: (1, "Not present", "high", ""),
    32: (1, "Not present", "high", ""),
    33: (3, "Two side", "high", ""),
    34: (4, "Sidewalk 0m to <1m from road", "medium", "A raised concrete curb/sidewalk is clearly visible along one side in most frames of this batch"),
    35: (6, "Informal path >=1m", "medium", ""),
    36: (1, "Not present", "high", ""),
    37: (6, "_None_", "high", ""),
    38: (4, "_None_", "high", ""),
    39: (1, "No road works", "high", ""),
    40: (4, "Not applicable (no school at the location)", "high", ""),
    41: (3, "Not applicable (no school at the location)", "high", ""),
}
append_batch("387813463_387813687_b2", "387813463_387813687", "unnamed road", b)
print("appended road2 b2")
